### ISSUE TITLE
Can you explain more clearly fonts ?

### ISSUE THREAD

**Issue by yusuf202021** [synspawacza/nier_automata_localization#4]
Whenever i edit *.MCD files  I can not see numbers and Ş,Ğ,Ü even "u" letter.Can you explain more clearly fonts ?

**Comment by synspawacza** [comment]
Fonts are handled in 2 ways: in a FNT file, or as part of a MCD file. FNT files are used for most of texts and contains all Latin-1 characters. MCD files on the other hand contains only characters actually used in the game.
Some of the fonts used in MCD files are the same as FNT fonts, but some fonts are used only in MCD: 02, 03, 08, 09, 10. These fonts are missing some characters. 

Script `prepare_fonts.sh` extracts character images from both FNT and MCD files (actual images are stored separately in WTP files). After running this script, `fonts` directory will contain all extracted character images. As said, some characters might be missing.

When generating MCD files using `put_strings_mcd.py`, both MCD file and texture containing characters will be generated. Each MCD file needs respective texture. `build_localization.sh` handle MCD, builds MCD and the texture, converts this texture to DDS and pack it into WTP file. 

If missing character is used in MCD file, `put_strings_mcd.py` Will return `No such file or directory` error message with filename of missing image. Missing characters need to be created manually - there is no other way around it, such images simply does not exist in the game.

**Comment by yusuf202021** [comment]
I've seen that this game was localized to russian as unofficial also a Turkish Translator group localized without character problem.My discord is Yusuf 2020#7624.By the way OmegaT gives error when copying this repo to OmegaT(Project file was not a file).So i edited your bash script in the beginning it was giving following eror
bash: ./tools/put_strings.py: /usr/bin/python3: bad interpreter: No such file or directory
Added "python" before "./tools_put_strings.py" it worked.I still changed a lots of things in scripts.My question is how i extract glyps of a font and add the unsupported character.I extracted glyps with fontforge python.When i added it it did not work.Can you contact me on Discord.All my problem is font.

**Comment by yusuf202021** [comment]
up

**Comment by synspawacza** [comment]
I'm not sure how Russian and Turkish translation dealt with characters, but based on what I've seen in screenshots of Russian translation, the new entire font was used rather than extracting glyphs from the game. 

Regarding Project file was not a file error: the idea is to create new OmegaT project and then add files from the repo, not use the repo as a OmegaT project.

I'm don't know why are you using fontforge. The glyphs are extracted as a png images.

Extracting fonts is done while running `prepare.sh` script (which runs `prepare_fonts.sh`) and works like this:
```
/data/*/*.dat+*.dtt -[unpack_dat.py data unpacked]-> /unpacked/*/*.mcd*+.bin+*.wta+...
prepare_fonts.sh:
/unpacked /font/*/*.ftb+*.dds -[unpack_font.py]-> /fonts/*/*.png
/unpacked /*/*.mcd+*.dds  -[unpack_font.py]-> /fonts/*/*.png
```

Missing characters (i.e. characters used in the translation, but not present in the original game) needs to be added manually, as a png file in respective subdirectory of `fonts`. Filename is hexadecimal value of the character code (for example, letter "ü" is `00fc.png`).

Images from the `fonts` directory are used in two ways: to generate new `*.fnt` files with respective textures and to generate new `*.mcd` files with respective textures.

`*.fnt` files are generated using `build_fonts.sh`. The file in the repo use Polish letters (ĄąĆćĘęŁłŃńŚśŹźŻż) and it needs to be edited to add glyphs that are actually needed and used.

`*.mcd` files are generated in `build_localization.sh`, together with other files. This should work, as long as proper glyph images are present in the `fonts` directory.

**Comment by yusuf202021** [comment]
Thank you.Such as "ğ" how do i extract this from any fonts.I do not already need anymore.Someone will help me when translating is over.He can change fonts.

**Comment by yusuf202021** [comment]
I used fontforge to extract characters from font as png.But it did not work
