### ISSUE TITLE
unpacking error

### ISSUE THREAD

**Issue by wanadoo2** [synspawacza/nier_automata_localization#6]
.

**Comment by synspawacza** [comment]
Hello,

`ImportError: cannot import name 'Image'` error looks like problem with python unable to load correct version of Pillow library. It might be old, unsupported PIL library being loaded instead of Pillow. You might need to uninstall PIL and reinstall Pillow.

Following command should help troubleshoot the issue:
```bash
python -m pip show Pillow #Pillow version from pip
python -m pip show PIL #PIL version (should be "not found")
python -c "import PIL; print(PIL.__version__)" #Pillow version from python code
```
