### ISSUE TITLE
 /usr/bin/python3: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by indra-constantine** [synspawacza/nier_automata_localization#7]
bash: ./tools/unpack.py: /usr/bin/python3: bad interpreter: No such file or directory

i running windows 10 64bit Latest update
and Python 3.10.7

**Comment by synspawacza** [comment]
Hello

Looks like bash script cannot find python executable.

Since you are using windows, I recommend using unix-like environment, e.g. WSL, Linux VM or Cygwin and use python from that environment. I tried using fresh WSL installation and `prepare.sh` worked fine, I just needed to install pillow python library.

You can also try changing shebang , e.g. `#!/usr/bin/python`, `#!/usr/bin/env python`.
